### ISSUE TITLE
Editable Time seems to default to 11am - doesn't persist to model

### ISSUE THREAD

**Issue by NullVoxPopuli** [AddJam/ember-cli-pickadate#11]
this is how I'm calling the time picker

``` emblem
    = pick-a-time date=(readonly value) on-selected=(action (mut value)) options=(readonly timeOptions)
```

![image](https://cloud.githubusercontent.com/assets/199018/11720393/fc4eaf0c-9f2c-11e5-8c15-f28de4835eb0.png)
Notice on the right, the time is 10:48, but the time field shows 11am

Changing the time field doesn't update the time on the model.

Here are my time options from the component.

``` javascript
  timeOptions: function() {
    return {
      editable: true,
      formatSubmit: 'HH:i',
    };
  }.property(),
```

**Comment by NullVoxPopuli** [comment]
I have a test for this one, that kinda shows the funky behavior:

my component integration test:

``` javascript
import {
  moduleForComponent, test
}
from 'ember-qunit';
import hbs from 'htmlbars-inline-precompile';

moduleForComponent('date-time-input',
  'Integration | Component | date-time-input', {
    integration: true
  });


test('Creates the text fields', function(assert) {
  var timeAsString =
    'Thu Dec 10 2015 09:24:21 GMT-0500 (Eastern Standard Time)';
  this.set('time', timeAsString);

  this.render(hbs `
    {{date-time-input value=time}}
  `);

  var fields = this.$('.row input');
  assert.equal(fields.length, 2);

  var expectedDate = '10 December, 2015'; //moment(this.get('time'), 'YYYY-MM-DD');
  var expectedTime = '09:24:21'; //moment(this.get('time'), 'HH:mm:ss');
  var actualDate = $(fields[0]).val();
  var actualTime = $(fields[1]).val();

  assert.equal(actualDate, expectedDate);
  assert.equal(actualTime, expectedTime);
});
```

my component:

``` javascript
import Ember from 'ember';

export default Ember.Component.extend({

  timeOptions: function() {
    return {
      editable: true,
    };
  }.property(),

  dateOptions: function() {
    return {
      selectMonths: true,
      selectYears: true,
      onSet: function(context) {
        this.close();
      }
    };
  }.property()


});
```

``` emblem
.row
  .small-6.columns
    /= date-picker date=date valueFormat='YYYY-MM-DD' allowBlank=false
    = pick-a-date date=(readonly value) nulls-date=true on-selected=(action (mut value)) options=(readonly dateOptions)
  .small-6.columns
    /= input type='time' placeholder='00:00' value=time
    = pick-a-time date=(readonly value) on-selected=(action (mut value)) options=(readonly timeOptions)

```

the results:

![image](https://cloud.githubusercontent.com/assets/199018/11720597/e2b8db70-9f2d-11e5-8f75-720330d1b160.png)

**Comment by NullVoxPopuli** [comment]
If I change the time picker to go back to that giant scrollable list, then the time is properly updated in the model. 

However, after the time picker closes, the date picker opens.... :-\

**Comment by chrissloey** [comment]
Hey, sorry I haven't had time to look at this until now.

I reproduced the problem with your example, using 9:24 as the time and it was rounded to 9:30. I solved the minutes being rounded by passing in `interval: 1` with the options - after that the input field shows 9:24 instead of 9:30. 

From the [pickadate.js docs](http://amsul.ca/pickadate.js/time/#formatting-rules) it looks like they don't support formatting the seconds. It might be worth raising an issue with them if that's important to you https://github.com/amsul/pickadate.js/

**Comment by NullVoxPopuli** [comment]
I think I'm just horridly confused now.

look at these test results (all I did was remove the seconds from the test, cause I don't really care about those): 
![image](https://cloud.githubusercontent.com/assets/199018/11841092/bf5fe5ac-a3c8-11e5-9686-e6ee82ce294b.png)

No idea how that's converting to what it is.

Here is my input date: `'Thu Dec 10 2015 09:24:21 GMT-0500 (Eastern Standard Time)';
`

**Comment by chrissloey** [comment]
Looks like it's converting to todays date/time which I guess could happen if the date it gets is somehow invalid or null.

Maybe it's because the input date is a string. Could you try changing this line in your test

```
this.set('time', timeAsString);
```

to this

```
this.set('time', new Date(timeAsString));
```

**Comment by NullVoxPopuli** [comment]
hey thanks! it works now: https://github.com/NullVoxPopuli/aeonvera-ui/commit/8092758380ba9b49f0413fa388c95c26bfa2d7ab

**Comment by chrissloey** [comment]
Awesome! :smile:
