### ISSUE TITLE
How do i pass the options object

### ISSUE THREAD

**Issue by 0000marcell** [AddJam/ember-cli-pickadate#12]
I'm lost on how do i pass the options object, examples in the readme file would be highly appreciated, lets say i want to change the months to the short version, showMonthsShort: true, i  don't know how do i pass this options :(

**Comment by chrissloey** [comment]
I think the last parameter of this example is what you're looking for

```
{{pick-a-date date=(readonly date)
    on-selected=(action (mut date))
    placeholder="Pick a date"
    options=(readonly extraPickadateOptions)}}
```

So if you had a template with that in it, you'd need to have the property `extraPickadateOptions` in the corresponding component or controller. The property could be:

```
extraPickadateOptions: {
  showMonthsShort: true
}
```

Does that work? :)

**Comment by 0000marcell** [comment]
Thx for the quick reply, i've solved the problem right after opening the issue, i've never seen this syntax before options=(readonly object), i still don't know why options=object doesn't work, anyway thx sir :)

**Comment by chrissloey** [comment]
Great :smile:

That syntax is more in line with Ember 2.0 - "data down, actions up". The emberjs blog goes over some of [it here](http://emberjs.com/blog/2015/05/10/run-up-to-two-oh.html).
