### ISSUE TITLE
Global options?

### ISSUE THREAD

**Issue by denchen** [AddJam/ember-cli-pickadate#13]
Is there a way to set global options for pickadate? I'm using the component in several different places in my app, and I have the same pickadate options set in all those places. I could write a mixin with my desired options that gets consumed by every controller that uses pickadate, which is fine, but it would be cleaner if I could set it, in say, `ember-cli-build.js` (I believe only `theme` is configurable there, correct?)

**Comment by chrissloey** [comment]
There isn't currently a way to set the options globally, but I think it would be good to add. I won't have time to work on this until next week some time, happy to accept a pull request implementing it in the  same way that the `theme` is currently configurable.

**Comment by chrissloey** [comment]
This is now possible in 1.3.0. Added details to the [README](https://github.com/AddJam/ember-cli-pickadate/blob/master/README.md#global-default-options).
