### ISSUE TITLE
Update pickadate library to latest version v4.0.0-0

### ISSUE THREAD

**Issue by urbany** [AddJam/ember-cli-pickadate#17]
Hi, I tried to update the bower dependency my self to pickadate#4.0.0-0 but I get an error

```
Error: ENOENT: no such file or directory, stat 'code/tmp/source_map_concat-input_base_path-EKwRYxkN.tmp/0/bower_components/pickadate/lib/picker.js'
```

I think this file has been renamed to: `bower_components/pickadate/lib/ui-picker.js`

**Comment by chrissloey** [comment]
You would need to update the imports in [index.js](https://github.com/AddJam/ember-cli-pickadate/blob/master/index.js)
