### ISSUE TITLE
Example of acceptance testing

### ISSUE THREAD

**Issue by visoft** [AddJam/ember-cli-pickadate#18]
Do you have an example of acceptance testing with ember-cli-pickadate? I tried using Ember's test helper `click`, but that doesn't open the date-picker. I've also tried filling in dates using the `fillIn` helper, but they don't get actually set, most likely because they are `readonly` fields.

**Comment by chrissloey** [comment]
I don't have any examples but I just tried it out and I think you'll need to use `andThen`

This failed:

```
    assert.equal(find('.picker__input--active').length, 0);
    click(find('.ember-pick-a-date'));
    assert.equal(find('.picker__input--active').length, 1);
```

This passed:

```
    assert.equal(find('.picker__input--active').length, 0);
    click(find('.ember-pick-a-date'));

    andThen(function() {
      assert.equal(find('.picker__input--active').length, 1);
    });
```

**Comment by chrissloey** [comment]
Closing this now, hope you got it working :)
