### ISSUE TITLE
Bug when selecting date when number of days in selected month is less than today (e.g. 31 March)

### ISSUE THREAD

**Issue by adrianwong81** [AddJam/ember-cli-pickadate#22]
For example today is 31 March. When I try to select any date in April (30 days) like 20 April, the result will become 20 May. The same thing happens for June (e.g. 20 June becomes 20 July).

After some debugging I believe the source of the bug appears to be the following 4 lines in the onSelected function:
      var newDate = new Date(date);
      newDate.setYear(dateItem.year);
      newDate.setMonth(dateItem.month);
      newDate.setDate(dateItem.date);

The following javascript illustrates the problem:
// Want to select 20 April 2016, the current date is 31 March 2016
testDate = new Date(2016, 2, 31); console.log(testDate); // 31 March 2016
testDate.setYear(2016); console.log(testDate); // 31 March 2016, so far so good
testDate.setMonth(3); console.log(testDate); // 1 May 2016, huh???
testDate.setDate(20); console.log(testDate); // 20 May 2016, not what we wanted

Further details about this javascript date "bug" can be found here:
http://stackoverflow.com/questions/14680396/the-date-getmonth-method-has-bug

To resolve this I recommend you replace the 4 lines previously mentioned with this:
      var newDate = new Date(dateItem.year, dateItem.month, dateItem.date);

**Comment by adrianwong81** [comment]
Or alternatively we could set the date to 1 before changing the month, that should have a minimal impact on the existing logic and allow us to keep the time of the original date object: 

var newDate = new Date(date);
newDate.setDate(1); // Prevent month wrapping bug (e.g. 31 April = 1 May)
newDate.setYear(dateItem.year);
newDate.setMonth(dateItem.month);
newDate.setDate(dateItem.date);

**Comment by chrissloey** [comment]
Hey, thanks for the detailed issue. Could you check you're on the latest version? v1.1.1 should have [fixed this](https://github.com/AddJam/ember-cli-pickadate/commit/f3f5e5379ab9142c12df591f7f975ac88e4aeeda) by setting the date before setting the month

**Comment by adrianwong81** [comment]
Hi Chris thanks a lot for the reply, however if we setDate before setMonth I think there can still be a subtle bug when we try to select dates with 31 when the current date is a month with less than 31 days. The following javascript illustrates the problem:

// Want to select 31 May 2016, the current date is 30 April 2016 (or any date in April, doesn't matter)
testDate = new Date(2016, 3, 30); console.log(testDate); // 30 April 2016
testDate.setYear(2016); console.log(testDate); // 30 April 2016, as expected
testDate.setDate(31); console.log(testDate); // 1 May 2016, not what we wanted
testDate.setMonth(4); console.log(testDate); // still 1 May 2016

I think at the moment setting the date to 1 before changing the month (comment #2) would be the safest change.

P.S. We're using v1.0.0 but I believe the bug was still in v1.1.1.

**Comment by adrianwong81** [comment]
Fyi still facing a bug on v1.2.0 and have created a pull request for the proposed fix for this issue.
