### ISSUE TITLE
Bug with 31th day

### ISSUE THREAD

**Issue by Stas-Buzunko** [AddJam/ember-cli-pickadate#26]
When I choose for the first time after refresh page the 31th of any month I get 1th of that month. If I choose then another date and after that come back to 31th it works fine. But for the first time after page refresh I get 1st of that month instead of 31th.

{{pick-a-date date=(readonly date) on-selected=(action (mut date)) placeholder="Pick a date" options=(readonly extraPickadateOptions)}}

**Comment by chrissloey** [comment]
What version of the addon are you using? I couldn't reproduce the problem.

**Comment by Stas-Buzunko** [comment]
"ember-cli-pickadate": "1.1.1"

**Comment by chrissloey** [comment]
Could you try 1.3.1 please?

1.2.1 was a bugfix related to something similar so I think updating to latest (1.3.1) will fix it.

**Comment by chrissloey** [comment]
Although worth noting that 1.3.1 is only compatible with Ember 2.5 and newer. If you're not on that, 1.2.1 should be fine.

**Comment by chrissloey** [comment]
I hope updating the addon fixed things for you, I'll open again if it hasn't.
