### ISSUE TITLE
error when using tag

### ISSUE THREAD

**Issue by zurnet** [AddJam/ember-cli-pickadate#27]
I get this error in the console:

> Error: Could not find module `ember-get-config` imported from `ember-cli-pickadate/components/picker`

**Comment by chrissloey** [comment]
Hey, thanks for reporting this! I moved `ember-get-config` from `devDependencies` to `dependencies`. Could you try v1.3.2 and let me know if it fixes things for you?

**Comment by zurnet** [comment]
Works!  Thank you.

**Comment by chrissloey** [comment]
Awesome :smile:
