### ISSUE TITLE
Fastboot compatibility

### ISSUE THREAD

**Issue by christophermlne** [AddJam/ember-cli-pickadate#33]
An Ember project will not build successfully if this addon is present in package.json

The Fastboot addon author guide has steps listed to ensure addon is compatible with Fastboot:
http://www.ember-fastboot.com/docs/addon-author-guide

**Comment by demersus** [comment]
I've opened a PR here: https://github.com/AddJam/ember-cli-pickadate/pull/34

**Comment by chrissloey** [comment]
Merged & released as 1.3.6
