### ISSUE TITLE
Conflicting translation file names error

### ISSUE THREAD

**Issue by NullVoxPopuli** [AddJam/ember-cli-pickadate#5]
Merge error: conflicting capitalizations:
pickadate/lib/translations/fa_IR.js in /home/me/Development/project/tmp/broccoli_merge_trees-input_base_path-k1PKjI4I.tmp/10
pickadate/lib/translations/fa_ir.js in /home/me/Development/project/tmp/broccoli_merge_trees-input_base_path-k1PKjI4I.tmp/10
Remove one of the files and re-add it with matching capitalization.
We are strict about this to avoid divergent behavior between case-insensitive Mac/Windows and case-sensitive Linux.

**Comment by chrissloey** [comment]
This is a problem with pickadate.js, see [https://github.com/amsul/pickadate.js/issues/685](https://github.com/amsul/pickadate.js/issues/685). They haven't released a new version with the fix yet, so for now we're using a fork to make our builds pass.

This is what we're using in our bower.json:

```
"pickadate": "AddJam/pickadate.js#cd23958028a62035bd684b9368eca4444805563d"
```

**Comment by NullVoxPopuli** [comment]
Thanks for the workaround!
