### ISSUE TITLE
Adding Options

### ISSUE THREAD

**Issue by rocketbop** [AddJam/ember-cli-pickadate#6]
I can't quite figure out how to get options working in ember-cli-build.js.

I've tried variations on, for example :

  var app = new EmberApp({
    "ember-cli-pickadate": {
      'disable': [
        1, 4, 7
      ]
    }
  });

Am I getting the format incorrect?

**Comment by chrissloey** [comment]
The only option supported in ember-cli-build.js is `theme` - that is a little misleading in the readme. I'll make it clearer.

For your use case, you'd need to pass the options directly to the component.

```
{{pick-a-date options=options}}
```

```
options:  {
  "disable": [1, 4, 7]
}
```

The options parameter is passed through directly to pickadate.js

Let me know if that solves your problem :smile:

**Comment by rocketbop** [comment]
Ah of course that makes sense, cheers :)

Although stil haven't got it quite working. I added an object as a computed property on my controller.

```
  extraPickadateOptions: Ember.computed(function () {
    return {
      min: new Date(2015,3,20),
      max: new Date(2015,7,14)
    }
  })
```

And I try and pass this into the component itself.
{{pickadate options=extraPickadateOptions}}

The object computes fine, but the component doesn't seem to get it in time. I get

Uncaught TypeError: Cannot read property 'onClose' of undefined

in the console, referring to the options variable. Why would that be I wonder ...

**Comment by rocketbop** [comment]
EDIT - I figured it out - I was forgetting to pass it through a parent component, I have nested coponent.

That's it, it's working great, thanks for your help! And cheers for wrapping the plugin :)

**Comment by chrissloey** [comment]
Awesome! thanks :)
